### ISSUE TITLE
Beaglebone Black Adapt to SHT31 temperature and humidity sensor

### ISSUE THREAD

**Issue by zyq5428** [Sensirion/embedded-sht#21]
I read the official website said that the HT version of the kernel supports the SHT3x driver,

SHT3x | 4.8 | June 2, 2016

 but I did not see the configuration of the SHT31 in the configuration, I am based on the website [https://www.digikey.com/eewiki/display/linuxonarm/BeagleBone+Black] configured BBB firmware. The kernel version is 4.18.

I have configured the relevant content in the device tree.

`&i2c1 {
	pinctrl-names = "default";
	pinctrl-0 = <&i2c1_pins>;

	status = "okay";
	clock-frequency = <100000>;

	sht31: sht31@44 {
		compatible = "sensirion,sht31";
		reg = <0x44>;
	};
};

debian@BBB:~$ sudo i2cdetect -r -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- 44 -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
debian@BBB:~$ `

How can I enable the SHT31 driver?

**Comment by abrauchli** [comment]
Dear @zyq5428 

I'll close this here since the question is not related to the embedded driver but to the upstream Linux driver.

We can't provide support but as a hint, what you likely need is the config option `CONFIG_SENSORS_SHT3x` to enable SHT31 support in your kernel config. Enable it either as module or compile it in. If you select the module option you'll need to load the `sht3x` module. You'll need to compile your own kernel if it's not shipped with the one you're using now.
