### ISSUE TITLE
Laziness in example programs confusing me...

### ISSUE THREAD

**Issue by Staok** [Sensirion/embedded-sht#81]
the fun "sht4x_read()" in "sht4x.c" should read out 6bytes of temp and hum data but not 4bytes

int16_t sht4x_read(int32_t* temperature, int32_t* humidity) {
    uint16_t words[2];
    ...

here is sames not correct according to the manual by the first view:

I2C bus operates with 8-bit data packages. Information from the sensor to the master has a checksum after 
every second 8-bit data package.  
Humidity and temperature data will always be transmitted in the following way: The first value is the 
temperature signal (2 * 8-bit data + 8-bit CRC), the second is the humidity signal (2 * 8-bit data + 8-bit CRC).

The master may abort a read transfer after the 16-bit data if it does not require a checksum.

Laziness in example programs confusing people...

and the uint32 data is 1000 times, by divide 1000 is float / double actual num is kinda not appear in the manual...
i looked it for several times,,

**Comment by abrauchli** [comment]
The bytes are correct. If you check out the driver code you can see that it's abstracted in sensirion_i2c_read_words_as_bytes where the CRC is read, checked and then discarded since you don't need it further down. If the CRC doesn't match you get an error back.
https://github.com/Sensirion/embedded-common/blob/1ac7c72c895d230c6f1375865f3b7161ce6b665a/sensirion_common.c#L110C9-L110C42

The multiplied by 1000 result is also documented in the driver header since it's a driver feature that has nothing to do with the sensor. This is done because some architectures (e.g. 8 bit) are much slower at processing doubles.
https://github.com/Sensirion/embedded-sht/blob/76cb6e6c00d381706d93e56e19c3a7ec3462be0f/sht4x/sht4x.h#L98

I think this can be closed.

**Comment by Staok** [comment]
It is not friendly for quick integration and use. It is not just a pair of .c and .h files, but a bunch of files. 
have to read and understand them. Then find that the method for calculating temperature and humidity is inconsistent with the device manual, then you found out its right after looking carefully. 
and then, you know what, time is consumed...
